name: Build For iOS

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [ Release, Debug ]
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: maxim-lobanov/setup-xcode@v1
        name: Setup Xcode
        with:
          xcode-version: latest-stable

      - name: Build
        run: |
          xcodebuild clean build \
            -project LLMFarm.xcodeproj \
            -scheme LLMFarm_Release clean archive -configuration ${{ matrix.configuration }} \
            -archivePath LLMFarm.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_IDENTITY=""

      - name: XCarchive to ipa
        run: |
          mkdir Payload
          cp -a LLMFarm.xcarchive/Products/Applications/* Payload
          zip -rmq "LLMFarm-${{ matrix.configuration }}.ipa" Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: LLMFarm-${{ matrix.configuration }}.ipa
