name: Xcode Build

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      ios-build-runner:
        description: 'Workflow runner for iOS build'
        required: true
        default: 'macos-12'
        type: choice
        options:
          - macos-11
          - macos-12
          - macos-13
          - macos-14
          - macos-latest
      macos-build-runner:
        description: 'Workflow runner for macOS build'
        required: true
        default: 'macos-12'
        type: choice
        options:
          - macos-11
          - macos-12
          - macos-13
          - macos-14
          - macos-latest
      ios-build-xcode-version:
        description: 'Xcode version for iOS build'
        required: true
        default: '14.1' # With iOS 16 SDK
        type: string
      macos-build-xcode-version:
        description: 'Xcode version for macOS build'
        required: true
        default: '14.1' # With macOS 13 SDK
        type: string

jobs:
  build-for-ios:
    strategy:
      matrix:
        configuration: [ Release, Debug ]
    runs-on: ${{ inputs.ios-build-runner }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: maxim-lobanov/setup-xcode@v1
        name: Setup Xcode
        with:
          xcode-version: ${{ inputs.ios-build-xcode-version }}

      - name: Build for iOS
        run: |
          xcodebuild clean build \
            -project LLMFarm.xcodeproj \
            -scheme LLMFarm_Release clean archive -configuration ${{ matrix.configuration }} \
            -archivePath LLMFarm.xcarchive \
            -sdk iphoneos \
            generic/platform=iOS \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_IDENTITY=""

      - name: XCarchive to ipa
        run: |
          mkdir Payload
          cp -a LLMFarm.xcarchive/Products/Applications/* Payload
          zip -rmq "LLMFarm-${{ matrix.configuration }}.ipa" Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS-${{ matrix.configuration }}
          path: |
            LLMFarm-${{ matrix.configuration }}.ipa

  build-for-macos:
    strategy:
      matrix:
        configuration: [ Release, Debug ]
    runs-on: ${{ inputs.macos-build-runner }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: maxim-lobanov/setup-xcode@v1
        name: Setup Xcode
        with:
          xcode-version: ${{ inputs.ios-build-xcode-version }}

      - name: Build
        run: |
          xcodebuild clean build \
            -project LLMFarm.xcodeproj \
            -scheme LLMFarm_Release clean archive \
            -configuration ${{ matrix.configuration }} \
            -archivePath LLMFarm.xcarchive \
            -sdk macosx \
            -arch x86_64 \
            -arch arm64 \
            -arch arm64e \
            generic/platform=macOS \
            ONLY_ACTIVE_ARCH=NO \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_IDENTITY=""

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-${{ matrix.configuration }}
          path: |
            LLMFarm.xcarchive/Products/Applications