name: Build For iOS

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        configuration: [ release, debug ]
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build
        run: |
          xcodebuild -project LLMFarm.xcodeproj \
            -scheme LLMFarm clean archive -configuration ${{ matrix.configuration }} \
            -archivePath LLMFarm.xcarchive

      - name: XCarchive to ipa
        run: |
          mkdir Payload
          cp -a LLMFarm.xcarchive/Products/Applications/* Payload
          zip -rmq "LLMFarm-${{ matrix.configuration }}.ipa" Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: LLMFarm-${{ matrix.configuration }}.ipa
